<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <artifactId>winterfell-parent</artifactId>
        <groupId>io.github.sixcrabs</groupId>
        <version>1.1.0</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>

    <groupId>io.github.sixcrabs</groupId>
    <artifactId>wf-ring-timer</artifactId>
    <version>1.1.0</version>
    <packaging>jar</packaging>

    <name>${project.artifactId}</name>
    <description> Java Ring Timer </description>
    <url>https://github.com/sixcrabs/winterfell</url>
    <licenses>
        <license>
            <name>MIT License</name>
            <url>https://opensource.org/licenses/MIT</url>
            <distribution>repo</distribution>
        </license>
    </licenses>
    <developers>
        <developer>
            <name>Alex</name>
            <email>parselife@gmail.com</email>
            <roles>
                <role>Project Manager</role>
                <role>Architect</role>
            </roles>
        </developer>
    </developers>
    <scm>
        <connection>scm:git:git://github.com/sixcrabs/winterfell.git</connection>
        <developerConnection>scm:git:ssh://github.com/sixcrabs/winterfell.git</developerConnection>
        <url>https://github.com/sixcrabs/winterfell</url>
    </scm>

    <dependencies>
        <dependency>
            <groupId>com.google.guava</groupId>
            <artifactId>guava</artifactId>
            <version>33.2.1-jre</version>
        </dependency>
        <dependency>
            <groupId>com.google.code.gson</groupId>
            <artifactId>gson</artifactId>
            <version>2.10.1</version>
        </dependency>
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-api</artifactId>
            <version>1.7.30</version>
        </dependency>
        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <version>4.13.1</version>
            <scope>test</scope>
        </dependency>
    </dependencies>


</project>