<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <artifactId>winterfell-parent</artifactId>
        <groupId>io.github.sixcrabs</groupId>
        <version>1.1.0</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>

    <groupId>io.github.sixcrabs</groupId>
    <artifactId>wf-hutool-mini</artifactId>
    <version>1.2.0</version>
    <packaging>jar</packaging>

    <name>${project.artifactId}</name>
    <description>Minimal Utils for Hutool.</description>
    <url>https://github.com/sixcrabs/winterfell</url>
    <licenses>
        <license>
            <name>The Apache Software License, Version 2.0</name>
            <url>https://www.apache.org/licenses/LICENSE-2.0.txt</url>
            <distribution>repo</distribution>
        </license>
    </licenses>
    <developers>
        <developer>
            <name>Alex</name>
            <email>parselife@gmail.com</email>
            <roles>
                <role>Project Manager</role>
                <role>Architect</role>
            </roles>
        </developer>
    </developers>
    <scm>
        <connection>scm:git:git://github.com/sixcrabs/winterfell.git</connection>
        <developerConnection>scm:git:ssh://github.com/sixcrabs/winterfell.git</developerConnection>
        <url>https://github.com/sixcrabs/winterfell</url>
    </scm>

    <properties>
        <maven.compiler.source>8</maven.compiler.source>
        <maven.compiler.target>8</maven.compiler.target>
        <bouncycastle.version>1.78.1</bouncycastle.version>
    </properties>

    <dependencies>
        <dependency>
            <groupId>com.google.guava</groupId>
            <artifactId>guava</artifactId>
            <version>33.2.1-jre</version>
        </dependency>

        <dependency>
            <groupId>org.bouncycastle</groupId>
            <artifactId>bcpkix-jdk18on</artifactId>
            <version>${bouncycastle.version}</version>
            <scope>compile</scope>
            <optional>true</optional>
        </dependency>
    </dependencies>

</project>