<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>io.github.sixcrabs</groupId>
        <artifactId>winterfell-parent</artifactId>
        <version>1.1.0</version>
    </parent>

    <artifactId>wf-starter-parent</artifactId>
    <packaging>pom</packaging>

    <modules>
        <module>app-spring-boot-starter</module>
        <module>app-spring-cloud-starter</module>
        <module>app-tongweb-starter</module>
        <module>app-vertx-starter</module>
        <module>app-javalin-starter</module>
        <module>minio-spring-boot-starter</module>
        <module>srpc-spring-boot-starter</module>
        <module>zinc-client-spring-boot-starter</module>
        <module>keystore-spring-boot-starter</module>
    </modules>

    <name>${project.artifactId}</name>
    <description>Spring Boot Starters for Winterfell Components</description>
    <url>https://github.com/sixcrabs/winterfell</url>
    <licenses>
        <license>
            <name>MIT License</name>
            <url>https://opensource.org/licenses/MIT</url>
            <distribution>repo</distribution>
        </license>
    </licenses>
    <developers>
        <developer>
            <name>Alex</name>
            <email>parselife@gmail.com</email>
            <roles>
                <role>Project Manager</role>
                <role>Architect</role>
            </roles>
        </developer>
    </developers>
    <scm>
        <connection>scm:git:git://github.com/sixcrabs/winterfell.git</connection>
        <developerConnection>scm:git:ssh://github.com/sixcrabs/winterfell.git</developerConnection>
        <url>https://github.com/sixcrabs/winterfell</url>
    </scm>

</project>